services:
  database:
    container_name: codevance_api_db
    image: postgres:16.3
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

  rbmq:
    container_name: codev_rabbitmq
    image: rabbitmq:3.13
    restart: no
    env_file: .env
    ports:
      - 5672:5672