# Generated by Django 5.0.7 on 2024-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
