# Generated by Django 5.0.7 on 2024-07-24 13:28

import codevance_api.payments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='new_due_date',
            field=models.DateField(validators=[codevance_api.payments.validators.date_not_before_today]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(validators=[codevance_api.payments.validators.date_not_before_today]),
        ),
    ]
