# Generated by Django 5.0.7 on 2024-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_anticipation_new_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('PC', 'Pending confirmation'), ('D', 'Denied')],
                                   default='PC', max_length=25),
        ),
    ]
