# Generated by Django 5.0.7 on 2024-07-25 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0003_alter_anticipation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Registered in')),
                ('action',
                 models.CharField(choices=[('A', 'Approval'), ('D', 'Denial'), ('R', 'Request')], max_length=8)),
                ('anticipation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.anticipation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
